AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vod-media-info

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  VodMediaInfo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: app/
      Handler: bootstrap
      Role: arn:aws:iam::067057696393:role/CMPLambdaTestRole
      Runtime: provided.al2023
      Environment:
        Variables:
          ACTIVE_ENV: dev
      FunctionName: cmp-lambda-vod-media-info

  VodMediaInfoLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${VodMediaInfo}
      RetentionInDays: 14

Outputs:
  VodMediaInfo:
    Description: "Lambda Function ARN"
    Value: !GetAtt VodMediaInfo.Arn
